[
    {
        "content": "<p>Twice in a row, CI failed because of issues with the cache: <a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/7741115780/job/21107736659\">https://github.com/leanprover-community/mathlib4/actions/runs/7741115780/job/21107736659</a></p>",
        "id": 419236070,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1706790622
    },
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/mathlib4/pull/10063\">#10063</a> is still not merged</p>",
        "id": 419236392,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1706790736
    },
    {
        "content": "<p>It's on the queue now</p>",
        "id": 419236566,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1706790807
    }
]