[
    {
        "content": "<p>It seems I've caused a seemingly unrelated test failure (test/RewriteSearch/Polynomial.lean) in a <a href=\"https://github.com/leanprover-community/mathlib4/pull/10234/files\">small PR</a> (specifically, starting from <a href=\"https://github.com/leanprover-community/mathlib4/pull/10234/commits/9efc8a00edf06179317f149fec9c9bef2baaed46\">this commit</a>). Does anyone know what it could be? It passes locally for me (<code>lake env lean test/RewriteSearch/Polynomial.lean</code>; I've also tried merging <code>master</code> and re-building). Did I perhaps cause it to timeout on CI?</p>",
        "id": 421396185,
        "sender_full_name": "llllvvuu",
        "timestamp": 1707900308
    },
    {
        "content": "<p>It looks like it finds <code>sub_eq_add_neg</code> while the test expects <code>sub_eq_neg_add</code>. I don't understand how either is expected to succeed.</p>",
        "id": 421397339,
        "sender_full_name": "Yury G. Kudryashov",
        "timestamp": 1707900770
    },
    {
        "content": "<p>UPD: I see</p>",
        "id": 421397374,
        "sender_full_name": "Yury G. Kudryashov",
        "timestamp": 1707900787
    },
    {
        "content": "<p>It starts with <code>natDegree_sub</code>, I missed that.</p>",
        "id": 421397409,
        "sender_full_name": "Yury G. Kudryashov",
        "timestamp": 1707900803
    },
    {
        "content": "<p>So, you've changed something, and it finds a different solution to the same problem now.</p>",
        "id": 421397647,
        "sender_full_name": "Yury G. Kudryashov",
        "timestamp": 1707900892
    },
    {
        "content": "<p>Last time it changed solution was in <a href=\"https://github.com/leanprover-community/mathlib4/pull/9083\">#9083</a>. <span class=\"user-mention\" data-user-id=\"110087\">@Scott Morrison</span> Should we have this unstable test at all?</p>",
        "id": 421397887,
        "sender_full_name": "Yury G. Kudryashov",
        "timestamp": 1707900970
    },
    {
        "content": "<p>Thanks, that fixed it! Seems related: <a href=\"https://github.com/leanprover-community/mathlib4/issues/9410\">https://github.com/leanprover-community/mathlib4/issues/9410</a></p>",
        "id": 421553088,
        "sender_full_name": "llllvvuu",
        "timestamp": 1707954250
    }
]