[
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"321696\">@Julian Berman</span> <span class=\"user-mention\" data-user-id=\"451983\">@Arthur Paulino</span> </p>\n<p>I encountered an extremely puzzling error.</p>\n<p>I was working to eliminate intentional errors in the code examples in the metaprogramming book. At that time, I found a code that did not cause an error on the lean4 web, but did locally. This is the following:</p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code><span class=\"kn\">import</span> <span class=\"n\">Lean</span>\n\n<span class=\"n\">elab</span> <span class=\"s2\">\"#assertType \"</span> <span class=\"n\">termStx</span><span class=\"o\">:</span><span class=\"n\">term</span> <span class=\"s2\">\" : \"</span> <span class=\"n\">typeStx</span><span class=\"o\">:</span><span class=\"n\">term</span> <span class=\"o\">:</span> <span class=\"n\">command</span> <span class=\"bp\">=&gt;</span>\n  <span class=\"kn\">open</span> <span class=\"n\">Lean</span> <span class=\"n\">Lean.Elab</span> <span class=\"n\">Command</span> <span class=\"n\">Term</span> <span class=\"k\">in</span>\n  <span class=\"n\">liftTermElabM</span>\n    <span class=\"n\">try</span>\n      <span class=\"k\">let</span> <span class=\"n\">tp</span> <span class=\"bp\">‚Üê</span> <span class=\"n\">elabType</span> <span class=\"n\">typeStx</span>\n      <span class=\"n\">discard</span> <span class=\"bp\">$</span> <span class=\"n\">elabTermEnsuringType</span> <span class=\"n\">termStx</span> <span class=\"n\">tp</span>\n      <span class=\"n\">synthesizeSyntheticMVarsNoPostponing</span>\n      <span class=\"n\">logInfo</span> <span class=\"s2\">\"success\"</span>\n    <span class=\"n\">catch</span> <span class=\"bp\">|</span> <span class=\"n\">_</span> <span class=\"bp\">=&gt;</span> <span class=\"n\">throwError</span> <span class=\"s2\">\"failure\"</span>\n\n<span class=\"sd\">/-- info: success -/</span>\n<span class=\"bp\">#</span><span class=\"n\">guard_msgs</span> <span class=\"k\">in</span>\n<span class=\"bp\">#</span><span class=\"n\">assertType</span> <span class=\"mi\">5</span>  <span class=\"o\">:</span> <span class=\"n\">Nat</span>\n\n<span class=\"sd\">/-- error: failure -/</span>\n<span class=\"bp\">#</span><span class=\"n\">guard_msgs</span> <span class=\"k\">in</span>\n<span class=\"bp\">#</span><span class=\"n\">assertType</span> <span class=\"o\">[]</span> <span class=\"o\">:</span> <span class=\"n\">Nat</span>\n</code></pre></div>\n<p>I noticed by chance that the name of the file in which the error occurs, <code>01_intro.lean</code>, was changed to <code>01intro.lean</code>, and the error no longer occurs!</p>\n<p>Note: my lean version is <code>v4.7.0</code></p>",
        "id": 433375439,
        "sender_full_name": "Asei Inoue",
        "timestamp": 1713211167
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"626349\">Asei Inoue</span> has marked this topic as resolved.</p>",
        "id": 433375454,
        "sender_full_name": "Notification Bot",
        "timestamp": 1713211172
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"626349\">Asei Inoue</span> has marked this topic as unresolved.</p>",
        "id": 433375468,
        "sender_full_name": "Notification Bot",
        "timestamp": 1713211177
    },
    {
        "content": "<p>why...?</p>",
        "id": 433375623,
        "sender_full_name": "Asei Inoue",
        "timestamp": 1713211214
    },
    {
        "content": "<p>First, I would like to know if this error is reproduced in other environments than mine.</p>",
        "id": 433375738,
        "sender_full_name": "Asei Inoue",
        "timestamp": 1713211246
    },
    {
        "content": "<p>This is a screenshot of errors. Unintelligible errors in unintelligible places ...</p>\n<p><a href=\"/user_uploads/3121/Crdka0-qzvPk6_yoeojSjCvu/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/3121/Crdka0-qzvPk6_yoeojSjCvu/image.png\" title=\"image.png\"><img src=\"/user_uploads/3121/Crdka0-qzvPk6_yoeojSjCvu/image.png\"></a></div>",
        "id": 433376041,
        "sender_full_name": "Asei Inoue",
        "timestamp": 1713211325
    },
    {
        "content": "<p>It was fixed while I was updating elan. I can't specify why it was fixed, but since the error no longer occurs, I'd like to assume that it is solved.</p>",
        "id": 433383224,
        "sender_full_name": "Asei Inoue",
        "timestamp": 1713213865
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"626349\">Asei Inoue</span> has marked this topic as resolved.</p>",
        "id": 433383230,
        "sender_full_name": "Notification Bot",
        "timestamp": 1713213867
    },
    {
        "content": "<p>Getting weird errors in weird places might be caused by <a href=\"https://github.com/leanprover/lean4/pull/3787\">lean4#3787</a>. This is fixed by restarting the file in the Lean server (or restarting the server).</p>",
        "id": 433706069,
        "sender_full_name": "Floris van Doorn",
        "timestamp": 1713344182
    }
]